### ISSUE TITLE
distutils is deprecated

### ISSUE THREAD

**Issue by alugowski** [GraphBLAS/python-suitesparse-graphblas#65] opened 2023-02-07 23:55 UTC
FYI, `distutils` (and setup.py) are deprecated and will be removed in Python 3.12. See https://docs.python.org/3.12/whatsnew/3.12.html

I've been impressed by scikit-build-core. https://github.com/scikit-build/scikit-build-core

**Comment by eriknw** [comment] 2023-02-08 01:31
+1000 to moving to a new build system such as `scikit-build-core` or `meson-python`.

We're actually using `setuptools`, not `distutils`, so the title of the issue isn't quite accurate, and Python 3.12 _probably_ shouldn't break us. Still, I'm happy to try to make things more modern.

In [`python-graphblas`](https://github.com/python-graphblas/python-graphblas/) we've moved everything to `pyproject.toml`. Since it's pure Python we still use the `setuptools.build_meta` build system and have a minimal [setup.py](https://github.com/python-graphblas/python-graphblas/blob/main/setup.py).

@alugowski, between this issue and your comment in https://github.com/GraphBLAS/python-suitesparse-graphblas/issues/64#issuecomment-1421641387, I think it's clear we share the same "ideal" target state: automatically building wheels on major platforms via `cibuildwheel` using scikit-build (and +1 if Windows can support complex). This is actually one of our [highest priorities](https://github.com/python-graphblas/python-graphblas/issues/360#issuecomment-1404610964).

@alugowski, any help you're able to offer here is greatly appreciated. I'd be thrilled if you can take the lead on this effort (if you'd like to), and I/we can off help as we're able. I have a _little_ bit of experience with cibuildwheel. Feel free to join the [`python-graphblas` weekly call](https://github.com/python-graphblas/python-graphblas/issues/247) or join our [discord](https://discord.com/invite/vur45CbwMz) ([#graphblas channel](https://discord.com/channels/786703927705862175/1024732940233605190)) to help us coordinate or to ask questions.

**Comment by alugowski** [comment] 2023-02-08 07:20
I've been working on it since the weekend and got it pretty much working: https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/66

**Comment by alugowski** [comment] 2023-02-08 07:42
I'm happy to help with `cibuildwheel`, but I'm not eager to take on a `scikit-build-core` conversion.  Especially since it sounds like it's not absolutely necessary.

**Comment by eriknw** [comment] 2023-03-31 17:44
I think we can close this issue. We have modernized to use `pyproject.toml` with `setuptools.build_meta` backend, and we automated building wheels with cibuildwheel (thanks for that @alugowski!).

**Closed by eriknw** 2023-03-31 17:44 UTC
